mendev_gui/mendev_gui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('system.urls')),
    path('admin/', admin.site.urls),
]

mendev_gui/system/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views


app_name = 'system'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('system/script/', views.script, name='script'),
    path('system/tasks/', views.tasks, name='tasks'),
    path('system/tasks/task/new/', views.task_new, name='task_new'),
    path('system/tasks/task/new/<copy_task_id>/', views.task_new, name='task_copy'),
    path('system/tasks/task/<task_id>/', views.task, name='task'),
    path('login/', auth_views.LoginView.as_view(template_name='system/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='system/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='system/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='system/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='system/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='system/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

mendev_gui/system/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import SysProfile, SysOrganisation
from django.utils.translation import gettext as _
from django.conf import settings


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label=_('First name'))
    last_name = forms.CharField(label=_('Last name'))
    email = forms.EmailField(label=_('Email'))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    language = forms.ChoiceField(
        label=_('Language'),
        choices=settings.LANGUAGES
    )
    organisation = forms.ModelChoiceField(
        label=('Organisation'),
        queryset=SysOrganisation.objects.all()
    )

    class Meta:
        model = SysProfile
        fields = ['language', 'organisation']

mendev_gui/system/views.py
import json
from datetime import datetime, timedelta

from _socket import gethostname
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.utils import timezone

from .forms import UserUpdateForm, ProfileUpdateForm
from .models import SysMenu, SysProfile, SysSetting, SysSubsystem, SysTaskType, SysTask
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext as _
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.conf import settings as system_settings
import requests


@login_required()
def profile(request):

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, f'Your profile is updated!')
            response = redirect('system:profile')
            response.set_cookie(key='django_language', value=request.user.profile.language)
            return response

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    if 'permitted_menu' not in request.session:
        request.session['permitted_menu'] = None
    main_menu = SysMenu.objects.get(name='MAIN')
    main_menu.prepare(request.path, request.user, request.session['permitted_menu'])
    context = {
        'main_menu': main_menu,
        'version': system_settings.VERSION,
        'user_form': user_form,
        'profile_form': profile_form,
        'title': 'Profile'
    }

    response = render(request, 'system/profile.html', context)
    response.set_cookie(key='django_language', value=request.user.profile.language)
    return response

def index(request):
    if 'permitted_menu' not in request.session:
        request.session['permitted_menu'] = None
    main_menu = SysMenu.objects.get(name='MAIN')
    main_menu.prepare(request.path, request.user, request.session['permitted_menu'])
    context = {
        'main_menu': main_menu,
        'version': system_settings.VERSION,
        'title': 'Home',
    }
    response = render(request, 'system/index.html', context)
    if not request.user.is_anonymous:
        try:
            response.set_cookie(key='django_language', value=request.user.profile.language)
        except:
            pass
    return response

def script(request):

    result = None
    script = 'return_value = "OK"'
    if 'script' in request.POST:
        script = request.POST['script']
    if 'confirmed' in request.POST and request.POST['confirmed'] == 'execute' and request.user.is_verified():
        try:
            script = request.POST['script']
            local_dict = locals()
            exec(script, globals(), local_dict)
            if 'return_value' in local_dict:
                result = local_dict['return_value']
        except Exception as error:
            messages.error(request, f"{error}")

    if 'permitted_menu' not in request.session:
        request.session['permitted_menu'] = None
    main_menu = SysMenu.objects.get(name='MAIN')
    main_menu.prepare(request.path, request.user, request.session['permitted_menu'])
    context = {
        'main_menu': main_menu,
        'title': 'Execute Script',
        'version': system_settings.VERSION,
        'script': script,
        'result': result
    }
    response = render(request, 'ttti/script.html', context)
    return response


@user_passes_test(lambda u: u.is_superuser)
def systeminfo(request):

    if 'api_key' not in request.session:
        settings = SysSetting.objects.get(key='gui', parent__isnull=True).settings()
        request.session['api_key'] = settings['api']['api_key']
        request.session['api_url'] = settings['api']['api_url']

    subsystems = []
    sys_subsystems = SysSubsystem.objects.all()
    for sys_subsystem in sys_subsystems:
        subsystem = {
            'name': sys_subsystem.name
        }
        if sys_subsystem.processor == 99:    # For local testing purposes
            url = f"http://127.0.0.1:8080//system/status"
        else:
            if sys_subsystem.processor == 1:
                url = f"{request.session['api_url']}/system/status/request"
            else:
                url = f"{request.session['api_url']}{sys_subsystem.processor}/system/status/request"
        try:
            r = requests.get(
                url=url,
                headers={
                    'Content-Type': 'application/json; charset=utf-8',
                    'x-api-key': request.session['api_key']
                }
            )
            r.raise_for_status()
        except Exception as error:
            subsystem['status'] = _('inactive')
            subsystem['error'] = f"Error connecting to '{url}', error: {error}"
        else:
            try:
                response = json.loads(r.text)
            except Exception as error:
                subsystem['status'] = error
            else:
                if 'errors' in response:
                    subsystem['status'] = response['errors'][0]
                else:
                    subsystem['active'] = True
                    subsystem['active_tasks_count'] = sys_subsystem.tasks_count(
                        ['running', 'waiting', 'started', 'submitted']
                    )
                    status = response['data']['status']
                    subsystem['status'] = _('active since ') + status['start_datetime']
                    subsystem['csx'] = status['csx']
                    subsystem['rbsrov'] = status['rbsrov']
                    subsystem['ttti_version'] = status['ttti_version']
                    subsystem['cpu_percentages'] = status['cpu_percentages']
                    subsystem['memory_total'] = round(status['virtual_memory']['total'] / 1024 / 1024)
                    subsystem['memory_used'] = round(status['virtual_memory']['used'] / 1024 / 1024)
                    subsystem['memory_percentage'] = status['virtual_memory']['percent']
                    subsystem['swap_memory_total'] = round(status['swap_memory']['total'] / 1024 / 1024)
                    subsystem['swap_memory_used'] = round(status['swap_memory']['used'] / 1024 / 1024)
                    subsystem['swap_memory_percentage'] = status['swap_memory']['percent']
        subsystems.append(subsystem)

    if 'permitted_menu' not in request.session:
        request.session['permitted_menu'] = None
    main_menu = SysMenu.objects.get(name='MAIN')
    main_menu.prepare(request.path, request.user, request.session['permitted_menu'])
    context = {
        'main_menu': main_menu,
        'title': 'System Information',
        'version': system_settings.VERSION,
        'application_server': gethostname(),
        'ttti_server': system_settings.DATABASES['default']['HOST'],
        'csx_server': system_settings.DATABASES['csx']['HOST'],
        'csx_database': system_settings.DATABASES['csx']['NAME'],
        'kv17_server': system_settings.DATABASES['kv17']['HOST'],
        'kv17_database': system_settings.DATABASES['kv17']['NAME'],
        'subsystems': subsystems
    }
    response = render(request, 'system/systeminfo.html', context)
    if not request.user.is_anonymous:
        try:
            response.set_cookie(key='django_language', value=request.user.profile.language)
        except:
            pass
    return response


@login_required()
@permission_required('system.view_task', raise_exception=True)
def tasks(request):
    if 'from_datetime' in request.POST:
        request.session['from_datetime_task'] = request.POST['from_datetime']
        if request.session['from_datetime_task'].count(':') == 1:
            request.session['from_datetime_task'] += ':00'
    if 'from_datetime_task' not in request.session or (request.method == 'GET' and 'init' in request.GET):
        request.session['from_datetime_task'] = timezone.now().strftime('%Y-%m-%dT00:00:00')
    if 'to_datetime' in request.POST:
        request.session['to_datetime_task'] = request.POST['to_datetime']
        if request.session['to_datetime_task'].count(':') == 1:
            request.session['to_datetime_task'] += ':00'
    if 'to_datetime_task' not in request.session or (request.method == 'GET' and 'init' in request.GET):
        request.session['to_datetime_task'] = (timezone.now() + timedelta(days=1)).strftime('%Y-%m-%dT00:00:00')

    if 'task_type_filter' in request.POST:
        request.session['task_type_filter'] = request.POST['task_type_filter']
    if 'task_type_filter' not in request.session or (request.method == 'GET' and 'init' in request.GET):
        request.session['task_type_filter'] = ''

    if 'requesting_user_filter' in request.POST:
        request.session['requesting_user_filter'] = request.POST['requesting_user_filter']
    if 'requesting_user_filter' not in request.session or (request.method == 'GET' and 'init' in request.GET):
        request.session['requesting_user_filter'] = ''

    if 'task_status_filter' in request.POST:
        request.session['task_status_filter'] = request.POST['task_status_filter']
    if 'task_status_filter' not in request.session or (request.method == 'GET' and 'init' in request.GET):
        request.session['task_status_filter'] = ''
    if 'task_order_by_list' not in request.session or (request.method == 'GET' and 'init' in request.GET):
        request.session['task_order_by_list'] = ['-id', 'task_type__name', 'status']
    if 'order_by' in request.POST:

mendev_gui/system/templates/system/index.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
<h2>MenDev Control</h2>
{% if user.is_authenticated %}
<div class="pb-3">{% trans 'Hello' %} {{ user.get_full_name }}!</div>
    {% for option in main_menu.options %}
      <div class="pt-1"><a class = "btn btn-primary btn-sm py-0" href="{{ option.url }}?init=true">{% trans option.name %}</a></div>
      {% for l1_option in option.options %}
        <div  class="pt-1 ps-1"><a class="btn btn-secondary btn-sm py-0" href="{{ l1_option.url }}?init=true">{% trans l1_option.name %}</a></div>
        {% for l2_option in l1_option.options %}
          <div  class="pt-1 ps-2"><a class="btn btn-dark btn-sm py-0" href="{{ l2_option.url }}?init=true">{% trans l2_option.name %}</a></div>
          {% for l3_option in l2_option.options %}
            <div  class="pt-1 ps-3"><a class="btn btn-light btn-sm py-0" href="{{ l3_option.url }}?init=true">{% trans l3_option.name %}</a></div>
          {% endfor %}
        {% endfor %}
      {% endfor %}
    {% endfor %}
{% else %}
  <p>{% trans 'You are not logged in' %}</p>
{% endif %}
{% endblock content %}

mendev_gui/system/templates/system/login.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'Login' %}</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">{% trans 'Login' %}</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'system:password_reset' %}">{% trans 'Forgotten password?' %}</a>
                </small>
            </div>
        </form>
    </div>
{% endblock content %}

mendev_gui/system/templates/system/logout.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
    <h2>{% trans 'You are logged out' %}</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'system:login' %}">{% trans 'Login again' %}</a>
        </small>
    </div>
{% endblock content %}

mendev_gui/system/templates/system/notification.html
{% extends "ttti_gui/base.html" %}
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>{% trans title %}</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <p class="notification-subject">{{ notification.subject }}</p>
            <div class="form-table">
                <div class="form-row">
                    <div class="form-element">
                        <div class="form-table">
                            <div class="form-row">
                                <label class="form-element">{% trans 'From'%}:</label>
                                <div  class="form-element">
                                    {% if notification.task %}
                                        <a class="underline"
                                            href="{% url 'ttti:task' notification.task.id %}">
                                            {{ notification.task.name }}
                                        </a>
                                    {% else %}
                                        {{ notification.created_by }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-row">
                                <label class="form-element">{% trans 'Sent To'%}:</label>
                                <div  class="form-element">
                                    {% for usernotification in notification.tttiusernotification_set.all %}
                                        {% if not forloop.first %}
                                            ,&nbsp;
                                        {% endif %}
                                        {{ usernotification.user.get_username }}
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-row">
                                <label class="form-element">{% trans 'Created'%}:</label>
                                <div  class="form-element">{{ notification.created_dt|date:'d-m-Y H:i:s' }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <p class="notification-content">{{ notification.content|default:''|linebreaks }}</p>
            <br><button class="btn btn-primary archive-button" type="submit" name="archive" value="archive"></button>
        </div>
    </form>
{% endblock content %}

mendev_gui/system/templates/system/notifications.html
{% extends "ttti_gui/base.html" %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
<script>
    function enterPage(event) {
        var key = event.which || event.keyCode;
        var form = event.currentTarget.form;
        if (key == 13) {
            form.submit();
        }
    }
</script>
<script>
    window.addEventListener("load", send_shown)
    function send_shown() {
        var host_url = window.location.origin
        notifications = document.getElementsByName("notif-row")
        for (notification of notifications) {
            var shown_datetime = notification.getAttribute("shown_datetime")
            if (shown_datetime == "None") {
                user_notification_id = notification.getAttribute('user_notification_id')
                fetch(host_url + "/notifications/shown/" + user_notification_id + "/")
                .then((response) => {
                    if (!response.ok) {
                        alert("Error setting notification shown.");
                    }
                })
            }
        }
    }
    function send_archive(el, user_notification_id) {
        var host_url = window.location.origin
        fetch(host_url + "/notifications/archive/" + user_notification_id + "/")
        .then((response) => {
            if (!response.ok) {
              alert("Error hiding notification.");
            }
            else {
                var to_hide = el.parentNode
                if (to_hide.tagName == "TD") {
                    to_hide = to_hide.parentNode;
                }
              to_hide.style.display='none';
            }
        })
    }
    function archive_all() {
        var from_datetime = document.getElementById("from_datetime").value
        var to_datetime = document.getElementById("to_datetime").value
        var host_url = window.location.origin
        fetch(host_url + "/notifications/archive_all/" + from_datetime + "/" + to_datetime + "/")
        .then((response) => {
            if (!response.ok) {
              alert("Error archiving notifications.");
            }
            else {
                location.reload();
            }
        })
    }
    function unarchive_all() {
        var from_datetime = document.getElementById("from_datetime").value
        var to_datetime = document.getElementById("to_datetime").value
        var host_url = window.location.origin
        fetch(host_url + "/notifications/unarchive_all/" + from_datetime + "/" + to_datetime + "/")
        .then((response) => {
            if (!response.ok) {
              alert("Error retrieving archived notifications.");
            }
            else {
                location.reload();
            }
        })
    }

</script>

<h2>{% trans title %}</h2>
<form method="POST" name="list">
{% csrf_token %}
    <div class="float-left mr-3">
        {% trans 'From' %}:
        <input id="from_datetime" type="datetime-local" name="from_datetime" step="1"
               value="{{ from_datetime|date:'Y-m-d' }}T{{ from_datetime|time:'H:i:s' }}">
    </div>
    <div class="float-left mr-3">
        {% trans 'To' %}:
        <input id="to_datetime" type="datetime-local" name="to_datetime" step="1"
               value="{{ to_datetime|date:'Y-m-d' }}T{{ to_datetime|time:'H:i:s' }}">
    </div>
    <div class="float-left mr-3">
        <button class="btn-primary" type="submit" name="select" value="select">{% trans 'Select' %}</button>
    </div>
    <div class="float-left mr-3">
        <button class="btn-primary archive_all" type="button" name="select" title="{% trans 'Archive all' %}"
                value="select" onclick="archive_all()"></button>
    </div>
    <div class="float-left mr-3">
        <button class="btn-primary unarchive_all" type="button" name="select" title="{% trans 'Retrieve archived' %}"
                value="select" onclick="unarchive_all()"></button>
    </div>
    <div class="small ml-5" style="clear:left;">({% trans 'Unshown notifications created before the selected period are shown once' %})</div>
    <table class="table table-sm">
        <tr>
            <th></th>
            <th scope="col" class="created_dt_col">
                <button class="order_by" type="submit" name="order_by" value="created_dt">
                    {% trans 'Created' %}
                </button>
            </th>
            <th scope="col" class="notification_from_col">{% trans 'From' %}</th>
            <th scope="col" class="subject_col">
                <button class="order_by" type="submit" name="order_by" value="notification__subject">
                    {% trans 'Subject' %}
                </button>
            </th>
        </tr>
    {% for user_notification in page_obj %}
        <tr context-info="{{ user_notification.record_info }}" name="notif-row" user_notification_id="{{ user_notification.id }}"
            shown_datetime="{{ user_notification.shown_datetime }}">
            <td onclick="send_archive(this, {{ user_notification.id }})">
              <div class="archive-icon"  title="{% trans 'Archive' %}"
                   onclick="send_archive(this, {{ user_notification.id }})">
              </div>
            </td>
            <td>{{ user_notification.created_dt|date:'d-m-Y H:i:s' }}</td>
            <td>
                {% if user_notification.notification.task %}
                <a class="underline"
                    href="{% url 'ttti:task' user_notification.notification.task.id %}">
                    {{ user_notification.notification.task.name }} ({{ user_notification.notification.task.id }})
                </a>
                {% else %}
                    {{ user_notification.created_by }}
                {% endif %}
            </td>
            <td class="subject" style="font-weight: {% if user_notification.shown_datetime %}normal{% else %}bold{% endif %}">
                <a class="underline" href="{% url 'ttti:notification' user_notification.notification.id %}">
                    {{ user_notification.notification.subject }}
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>
</form>
<div class="pagination">
    {% include "ttti_gui/pagination.html" %}
</div>
{% endblock content %}

mendev_gui/system/templates/system/password_reset.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'Reset password' %}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">{% trans 'Request password reset' %}</button>
            </div>
        </form>
    </div>
{% endblock content %}

mendev_gui/system/templates/system/password_reset_complete.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
    <div class="alert alert-info">
        {% trans 'Your password is reset' %}
    </div>
    <a href="{% url 'login' %}">{% trans 'Login here' %}</a>
{% endblock content %}

mendev_gui/system/templates/system/password_reset_confirm.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'Reset password' %}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">{% trans 'Set Password' %}</button>
            </div>
        </form>
    </div>
{% endblock content %}

mendev_gui/system/templates/system/password_reset_done.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
    <div class="alert alert-info">
        {% trans 'A mail is sent with instructions to reset the password.' %}
    </div>
{% endblock content %}

mendev_gui/system/templates/system/profile.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            {{ user_form }}
            {{ profile_form }}
            <div class="form-group">
                <br><button class="btn btn-outline-info" type="submit">{% trans 'Save' %}</button>
            </div>
        </form>
    </div>
{% endblock content %}

mendev_gui/system/templates/system/tasks.html
{% extends "mendev_gui/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
<script>
    function enterPage(event) {
        var key = event.which || event.keyCode;
        var form = event.currentTarget.form;
        if (key == 13) {
            form.submit();
        }
    }
</script>

<h2>{% trans title %}</h2>
<form method="POST" name="list">
{% csrf_token %}
    <div class="float-start me-3 mb-3">
        {% trans 'From' %}:
        <input type="datetime-local" name="from_datetime" step="1"
               value="{{ from_datetime|date:'Y-m-d' }}T{{ from_datetime|time:'H:i:s' }}">
    </div>
    <div class="float-start me-3 mb-3">
        {% trans 'To' %}:
        <input type="datetime-local" name="to_datetime" step="1"
               value="{{ to_datetime|date:'Y-m-d' }}T{{ to_datetime|time:'H:i:s' }}">
    </div>
    <div class="float-start me-3 mb-3">
        <button class="btn-primary" type="submit" name="select" value="select">{% trans 'Select' %}</button>
    </div>
    <table class="table table-sm">
        <tr>
            <th scope="col" class="task_id_col">
                <button class="order_by" type="submit" name="order_by" value="id">
                    {% trans 'ID' %}
                </button>
            </th>
            <th scope="col" class="task_type_col">
                <button class="order_by" type="submit" name="order_by" value="task_type__name">
                    {% trans 'Task Type' %}
                </button>
            </th>
            <th scope="col" class="started_dt_col">
                <button class="order_by" type="submit" name="order_by" value="datetime_started">
                    {% trans 'Started' %}
                </button>
            </th>
            <th scope="col" class="requesting_user_col">
                <button class="order_by" type="submit" name="order_by" value="requesting_user">
                    {% trans 'Requester' %}
                </button>
            </th>
            <th scope="col" class="status_col">
                <button class="order_by" type="submit" name="order_by" value="status">
                    {% trans 'Status' %}
                </button>
            </th>
            <th scope="col" class="logging_button_col">{% trans 'Subsystem' %}</th>
            <th scope="col" class="logging_button_col">{% trans 'Result' %}</th>
        </tr>
       <tr>
            <td></td>
            <td>
                <select name="task_type_filter"
                       onchange="this.form.submit()" class="task_type_filter">
                    <option value=""></option>
                    {% for option in task_type_filter_options %}
                        <option value="{{ option.id }}" {{ option.selected }}>{{ option.name }}</option>
                    {% endfor %}
                </select>
            </td>
            <td></td>
            <td><input type="text" name="requesting_user_filter" value="{{ requesting_user_filter }}"
                onkeypress="enterPage(event)" class="requesting_user_filter">
            </td>
            <td>
                <select name="task_status_filter"
                       onchange="this.form.submit()" class="task_status_filter">
                    <option value=""></option>
                    {% for option in status_filter_options %}
                        <option value="{{ option.status }}" {{ option.selected }}>{{ option.status }}</option>
                    {% endfor %}
                </select>
            </td>
            <td></td>
            <td></td>
        </tr>
    {% for task in page_obj %}
        <tr context-info="{{ task.record_info }}">
            <td><a title="{{ task.name }}" class="underline" href="{% url 'system:task' task.id %}">{{ task.id }}</a></td>
            <td>{{ task.task_type.name }}</td>
            <td>{{ task.datetime_started|date:'Y-m-d H:i:s' }}</td>
            <td>{{ task.requesting_user }}</td>
            <td>{{ task.status }}</td>
            <td>{{ task.task_type.subsystem.name }}</td>
            <td>{{ task.result|default_if_none:'' }}</td>
        </tr>
    {% endfor %}
    </table>
</form>
<div class="pagination">
    {% include "mendev_gui/pagination.html" %}
</div>
{% endblock content %}