mendev_gui/mendev_gui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('system.urls')),
    path('admin/', admin.site.urls),
]

mendev_gui/system/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views


app_name = 'system'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('system/script/', views.script, name='script'),
    path('system/tasks/', views.tasks, name='tasks'),
    path('system/tasks/task/new/', views.task_new, name='task_new'),
    path('system/tasks/task/new/<copy_task_id>/', views.task_new, name='task_copy'),
    path('system/tasks/task/<task_id>/', views.task, name='task'),
    path('login/', auth_views.LoginView.as_view(template_name='system/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='system/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='system/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='system/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='system/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='system/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

mendev_gui/templates/mendev_gui/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    {% if title %}
        <title>MenDev Control - {% trans title %}</title>
    {% else %}
        <title>Mendev Control</title>
    {% endif %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <script>
    window.onbeforeunload = function() {
      document.cookie = "window_innerheight=" + window.innerHeight + "; path=/;"
    }
  </script>

</head>
<body>
<div class="container-fluid ps-0 pe-0">
    <div class="top-row">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark ">
                <div class="container">
                    <div class="row">
                        <div class="col ps-0">
                            {% if not main_menu %}
                                <a class="navbar-brand" href="{% url 'system:index' %}">
                                    <img src="{% static 'mendev_button_logo.png' %}"/>
                                </a>
                            {% else %}
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                        aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                        {% if main_menu.num_options == 0 %}
                                            <li class="nav-item">
                                                <a class="nav-link" href="{{ main_menu.url }}">
                                                    <img src="{% static 'mendev_button_logo.png' %}"/>
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="{{ main_menu.url }}"
                                                        id="navbarDropdown_{{ main_menu.id }}" role="button"
                                                        data-bs-toggle="dropdown" aria-expanded="false">
                                                    <img src="{% static 'mendev_button_logo.png' %}"/>
                                                </a>
                                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown_{{ main_menu.id }}">
                                                    {% for option in main_menu.options %}
                                                        <li>
                                                            <a class="dropdown-item" href="{{ option.url }}">
                                                                {% trans option.name %}
                                                            </a>
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endif %}
                                        {% if main_menu.l1_menu %}
                                            {% if main_menu.l1_menu.num_options == 0 %}
                                                <li class="nav-item">
                                                    <a class="nav-link" href="{{ main_menu.l1_menu.url }}">
                                                        {% trans main_menu.l1_menu.name %}
                                                    </a>
                                                </li>
                                            {% else %}
                                                <li class="nav-item dropdown">
                                                    <a class="nav-link dropdown-toggle" href="{{ main_menu.l1_menu.url }}"
                                                       id="navbarDropdown_{{ main_menu.l1_menu.id }}" role="button"
                                                       data-bs-toggle="dropdown" aria-expanded="false">
                                                        {% trans main_menu.l1_menu.name %}
                                                    </a>
                                                    <ul class="dropdown-menu"
                                                            aria-labelledby="navbarDropdown_{{ main_menu.l1_menu.id }}">
                                                        {% for option in main_menu.l1_menu.options %}
                                                            <li>
                                                                <a class="dropdown-item" href="{{ option.url }}">
                                                                    {% trans option.name %}
                                                                </a>
                                                            </li>
                                                        {% endfor %}
                                                    </ul>
                                                </li>
                                            {% endif %}
                                        {% endif %}
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-3 d-flex align-items-center">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">login</li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="container pt-3">
          {# Display django.contrib.messages as Bootstrap alerts #}
          {% bootstrap_messages %}
    </div>
    <div class="container">
            {# Show app content #}
            {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

mendev_gui/templates/mendev_gui/base_ba.html
{% load static %}
{% load bootstrap5 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    {% if title %}
        <title>MenDev Control - {% trans title %}</title>
    {% else %}
        <title>Mendev Control</title>
    {% endif %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <script>
    window.onbeforeunload = function() {
      document.cookie = "window_innerheight=" + window.innerHeight + "; path=/;"
    }
  </script>

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top py-0 py-md-0">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                  aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!-- Level 0 menu -->
              <div class="btn-group py-0">
                {% if main_menu %}
                  <a  href="{{ main_menu.url }}" class="btn btn-secondary btn-sm py-0"><img src="{% static 'mendev_button_logo_small.png' %}"/></a>
                  {% if main_menu.num_options > 0 %}
                  <button class="btn btn-secondary btn-sm py-0 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                  </button>
                  <div class="dropdown-menu">
                    {% for option in main_menu.options %}
                      <a class="dropdown-item btn btn-sm py-0" href="{{ option.url }}">{% trans option.name %}</a>
                    {% endfor %}
                  </div>
                  {% endif %}
                {% else %}
                  <a  href="{% url 'system:index' %}" class="btn btn-secondary btn-sm py-0"><img src="{% static 'mendev_button_logo.png' %}"/></a>
                {% endif %}
              </div>
              <!-- Level 1 menu -->
              {% if main_menu.l1_menu %}
              <span class="main-menu-seperator">&gt;</span>
              <div class="btn-group">
                <a  href="{{ main_menu.l1_menu.url }}" class="btn btn-secondary btn-sm py-0">{% trans main_menu.l1_menu.name %}</a>
                {% if main_menu.l1_menu.num_options > 0 %}
                  <button class="btn btn-secondary btn-sm py-0 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only"></span>
                  </button>
                  <div class="dropdown-menu">
                    {% for option in main_menu.l1_menu.options %}
                      <a class="dropdown-item" href="{{ option.url }}">{% trans option.name %}</a>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
              {% endif %}
              <!-- Level 2 menu -->
              {% if main_menu.l2_menu %}
              <span class="main-menu-seperator">&gt;</span>
              <div class="btn-group">
                <a  href="{{ main_menu.l2_menu.url }}" class="btn btn-secondary btn-sm py-0">{% trans main_menu.l2_menu.name %}</a>
                {% if main_menu.l2_menu.num_options > 0 %}
                  <button class="btn btn-secondary btn-sm py-0 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only"></span>
                  </button>
                  <div class="dropdown-menu">
                    {% for option in main_menu.l2_menu.options %}
                      <a class="dropdown-item" href="{{ option.url }}">{% trans option.name %}</a>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
              {% endif %}
              <!-- Level 3 menu -->
              {% if main_menu.l3_menu %}
              <span class="main-menu-seperator">&gt;</span>
              <div class="btn-group">
                <a  href="{{ main_menu.l3_menu.url }}" class="btn btn-secondary btn-sm py-0">{% trans main_menu.l3_menu.name %}</a>
                {% if main_menu.l3_menu.num_options > 0 %}
                  <button class="btn btn-secondary btn-sm py-0 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only"></span>
                  </button>
                  <div class="dropdown-menu ml-2">
                    {% for option in main_menu.l3_menu.options %}
                      <a class="dropdown-item" href="{{ option.url }}">{% trans option.name %}</a>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
              {% endif %}
              <!-- Level 4 menu -->
              {% if main_menu.l4_menu %}
              <span class="main-menu-seperator">&gt;</span>
              <div class="btn-group">
                <a  href="{{ main_menu.l4_menu.url }}" class="btn btn-secondary btn-sm py-0">{% trans main_menu.l4_menu.name %}</a>
                {% if main_menu.l4_menu.num_options > 0 %}
                  <button class="btn btn-secondary btn-sm py-0 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only"></span>
                  </button>
                  <div class="dropdown-menu">
                    {% for option in main_menu.l4_menu.options %}
                      <a class="dropdown-item" href="{{ option.url }}">{% trans option.name %}</a>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'system:profile' %}">{{ user.get_username }}</a>
                <a class="nav-item nav-link" href="{% url 'system:logout' %}">{% trans 'Logout' %}</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'system:login' %}">{% trans 'Login' %}</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

</body>
</html>

mendev_gui/templates/mendev_gui/pagination.html
<form method="GET" name="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="pagination-arrow" href="?page=1">&lt;&lt;</a>
            <a class="pagination-arrow" href="?page={{ page_obj.previous_page_number }}">&lt;&nbsp;</a>
        {% endif %}

        <span class="current">
            <input name="page" type="number" value="{{ page_obj.number }}" onkeypress="enterPage(event)"
                   class="page-number-input"> / {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a class="pagination-arrow" href="?page={{ page_obj.next_page_number }}">&nbsp;&gt;</a>
            <a class="pagination-arrow" href="?page={{ page_obj.paginator.num_pages }}">&gt;&gt;</a>
        {% endif %}
    </span>
</form>